### ISSUE TITLE
AdminCP redirect issue 

### ISSUE THREAD

**Issue by zzxzz** [Ahmed2Game/Tatar-War#1]
السلام عليكم،، اشكرك على طرح النسخة

ولكن هناك مشكلة عند المحاوله في فتح لوحة التحكم 

https://www.hatom.net.sa/AdminCP/login

حيث ان login غير موجود لذى لوحة التحكم لا تفتح

**Comment by Ahmed2Game** [comment]
I update the script you can download it again and use README for install steps

**Comment by zzxzz** [comment]
Thank you so much for your response, I did all your instruction, but I got this error https://hatom.net.sa

Fatal error: Uncaught Error: Access to undeclared static property: Router::$config_dir in /home/hatomnet/public_html/system/library/Router.php:19 Stack trace: #0 /home/hatomnet/public_html/system/library/Loader.php(51): Router->__construct() #1 /home/hatomnet/public_html/Applic/bootstrap.php(64): Loader->auto_load_controller() #2 /home/hatomnet/public_html/index.php(22): require_once('/home/hatomnet/...') #3 {main} thrown in /home/hatomnet/public_html/system/library/Router.php on line 19

**Comment by Ahmed2Game** [comment]
I update router file so please make pull again or download

**Comment by zzxzz** [comment]
Hi again,

I'm sorry for bothering you again, but I updated the codes and I got this issue 

https://www.hatom.net.sa/

https://www.hatom.net.sa/AdminCP

Failed to open the website

**Comment by Ahmed2Game** [comment]
first download script again i fix some problems but your problems from your host please sure you active htaccess on server

**Comment by zzxzz** [comment]
I appreciate your effort Ahmed, Thank you so much for your work.

Now everything works good, but there is an issue message appeared in the header of Admin panel

Notice: Undefined index: plus in /AdminCP/app/bootstrap.php on line 37
Notice: Undefined index: troop in /AdminCP/app/bootstrap.php on line 38


you can check via this link 

http://www.hatom.net.sa/AdminCP

**Comment by Ahmed2Game** [comment]
yes there is problems in admin menu in Players tap but the another two problems will go when you install first server i see that fix in your side about another fix of menu please download script again 
thanks

**Comment by zzxzz** [comment]
Hello, again ^_^

Yes now the issue is solved, but can you check this one 

http://www.hatom.net.sa/AdminCP/quicktasks?page=news

Fatal error: Call to a member function prepare() on a non-object in /home/hatomnet/public_html/AdminCP/system/library/DB.php on line 43

and please can you try to create an account as a player here 

http://hatom.net.sa

because there is no redirect when I create an account.

Thank you

**Comment by Ahmed2Game** [comment]
This problem in php version. what is your php version?

**Comment by zzxzz** [comment]
PHP 5.4

**Comment by Ahmed2Game** [comment]
you need to install php 7.1 minimum

**Comment by zzxzz** [comment]
Ok I will do that right now

**Comment by zzxzz** [comment]
I found php 7.0 and when I applied on my server the website shut down and show to me failed to open

are you sure about the php version, or need to upgrade to 7.1 to load normally?

**Comment by zzxzz** [comment]
I have enabled PHP 7.1 for hatom.net.sa. The site shows the following error now.

http://www.hatom.net.sa

Fatal error: Uncaught Error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /home/hatomnet/public_html/system/library/DB2.php:28 Stack trace: #0 /home/hatomnet/public_html/system/library/Loader.php(192): DB2::init() #1 /home/hatomnet/public_html/Applic/bootstrap.php(28): Loader->init_db2() #2 /home/hatomnet/public_html/index.php(22): require_once('/home/hatomnet/...') #3 {main} thrown in /home/hatomnet/public_html/system/library/DB2.php on line 28

**Comment by Ahmed2Game** [comment]
problem in php_pdo_mysql search in google need to make some changes in php.ini file
